name = "memebot"
main = "./src/server.js"
compatibility_date="2022-02-26"
account_id = "8e539c8119fbacd649c0c41cad2830d5"
workers_dev = true
node_compat = true

[[rules]]
type = "ESModule"
globs = [ "**/*.js" ]

[env.dev]

[env.production]

# [secrets]
# DISCORD_TOKEN
# DISCORD_PUBLIC_KEY
# DISCORD_APPLICATION_ID
# DISCORD_TEST_GUILD_ID
